import img1 from "./assets/images/image1.jpg"
import img2 from "./assets/images/image2.jpg"
import img3 from "./assets/images/image3.jpg"
import buyerImg from "./assets/images/buyer.png"
import supplierImg from "./assets/images/supplier.png"
import imgQ1 from "./assets/images/(1).jpg"
import imgQ2 from "./assets/images/(2).jpg"
import imgQ3 from "./assets/images/(3).jpg"
import imgQ4 from "./assets/images/(4).jpg"
import imgQ5 from "./assets/images/(5).jpg"
import imgQ6 from "./assets/images/(6).jpg"
import imgQ7 from "./assets/images/(7).jpg"
import imgQ8 from "./assets/images/(8).jpg"
import imgQ9 from "./assets/images/(9).jpg"
import imgQ10 from "./assets/images/(10).jpg"
import imgQ11 from "./assets/images/(11).jpg"
// products images
import prod1 from "./assets/images/product 1.jpg"
import prod2 from "./assets/images/product 2.jpg"
import prod3 from "./assets/images/product 3.jpg"
import prod4 from "./assets/images/product 4.jpg"
import prod5 from "./assets/images/product 5.jpg"
import prod6 from "./assets/images/product 6.jpg"
import prod7 from "./assets/images/product 7.jpg"
import prod8 from "./assets/images/product 8.jpg"



export const quotations = [
    {
        id: "00",
        srcImg : img1,
        name: 'Grey fabrica & materials',
        Img: img1 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 1",
        quantity: "1000 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    },
    {
        id: "01",
        srcImg : img2,
        name: 'Grey fabrica & materials',
        Img: img2 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 2",
        quantity: "500 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5 ,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    },
    {
        id: "02",
        srcImg : img3,
        name: 'Grey fabrica & materials',
        Img: img3 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 3",
        quantity: "4000 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    },
    {
        id: "03",
        srcImg : img2,
        name: 'Grey fabrica & materials',
        Img: img2 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 4",
        quantity: "1000 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    },
    {
        id: "04",
        srcImg : img1,
        name: 'Grey fabrica & materials',
        Img: img1 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 1",
        quantity: "1000 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    },
    {
        id: "05",
        srcImg : img2,
        name: 'Grey fabrica & materials',
        Img: img2 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 2",
        quantity: "500 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5 ,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    },
    {
        id: "06",
        srcImg : img3,
        name: 'Grey fabrica & materials',
        Img: img3 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 3",
        quantity: "4000 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    },
    {
        id: "07",
        srcImg : img2,
        name: 'Grey fabrica & materials',
        Img: img2 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 4",
        quantity: "1000 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    },
    {
        id: "08",
        srcImg : img1,
        name: 'Grey fabrica & materials',
        Img: img1 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 1",
        quantity: "1000 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    },
    {
        id: "09",
        srcImg : img2,
        name: 'Grey fabrica & materials',
        Img: img2 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 2",
        quantity: "500 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5 ,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    },
    {
        id: "10",
        srcImg : img3,
        name: 'Grey fabrica & materials',
        Img: img3 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 3",
        quantity: "4000 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    },
    {
        id: "11",
        srcImg : img2,
        name: 'Grey fabrica & materials',
        Img: img2 ,
        location: 'Lesch Field',
        rating: 347 ,
        star: 4.5 ,
        product : "Product 4",
        quantity: "1000 Unit",
        buyerLocation: "Lesch Field",
        buyerName: "Grey fabrica & materials",
        buyerImg: buyerImg,
        buyerEvaluation: "347 تقييم",
        buyerrating: 4.5,
        supplierLocation: "Lesch Field",
        supplierName: "Grey fabrica & materials",
        supplierImg: supplierImg,
        supplierEvaluation: "347 تقييم",
        supplierrating: 4.5 ,
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD',
        paymentTerms : '30 day'
    }
]

export const requests = [
    {
        id: "01",
        Img : imgQ1,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "02",
        Img : imgQ2,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "03",
        Img : imgQ3,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "04",
        Img : imgQ4,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "05",
        Img : imgQ5,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "06",
        Img : imgQ6,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "07",
        Img : imgQ7,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "08",
        Img : imgQ8,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "09",
        Img : imgQ9,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "10",
        Img : imgQ10,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "11",
        Img : imgQ11,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "12",
        Img : imgQ1,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "13",
        Img : imgQ2,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "14",
        Img : imgQ3,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "15",
        Img : imgQ4,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "16",
        Img : imgQ5,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "17",
        Img : imgQ6,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "18",
        Img : imgQ7,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "19",
        Img : imgQ8,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "20",
        Img : imgQ9,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "21",
        Img : imgQ10,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
    {
        id: "22",
        Img : imgQ11,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        paymentTerms : '30 month',
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
    } ,
]

export const rfi = [
    {
        id: "01",
        Img : imgQ1,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        response: 'Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.',
        productImage: prod1,
        isCertified: true
    } ,
    {
        id: "02",
        Img : imgQ1,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        response: 'Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.',
        productImage: prod1,
        isCertified: true
    } ,
    {
        id: "03",
        Img : imgQ1,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        response: 'Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.Thank you for your inquiry regarding [details of the inquiry]. We are pleased to confirm that our company offers the solutions you are.',
        productImage: prod1,
        isCertified: true
    }
]

export const rfp = [
    {
        id: "01",
        Img : imgQ1,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        productName: "Clean - 0 ( 10 % sodium hydroxide )",
        content: "10 Wt % sodium Hydroxide",
        size: "Bottles: 1 Liter , 2 Liter ,20 Liter ,30 Liter",
        specialNotes: "Technical Specifications: Details about the specifications that the product or service must comply with",
        productImage: prod1,
    } ,
    {
        id: "02",
        Img : imgQ1,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        productName: "Clean - 0 ( 10 % sodium hydroxide )",
        content: "10 Wt % sodium Hydroxide",
        size: "Bottles: 1 Liter , 2 Liter ,20 Liter ,30 Liter",
        specialNotes: "Technical Specifications: Details about the specifications that the product or service must comply with",
        productImage: prod1,
    } ,
    {
        id: "03",
        Img : imgQ1,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        productName: "Clean - 0 ( 10 % sodium hydroxide )",
        content: "10 Wt % sodium Hydroxide",
        size: "Bottles: 1 Liter , 2 Liter ,20 Liter ,30 Liter",
        specialNotes: "Technical Specifications: Details about the specifications that the product or service must comply with",
        productImage: prod1,
    } ,
]

export const rfq = [
    {
        id: "01",
        Img : imgQ1,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        shippingTerms: 'FOB',
        leadTime: '4 Week',
        paymentTerms: 'Cash',
        products:  [
            {
                product: 'Steel pipes',
                offeredQuantity: '100 Unit',
                weightUnit: '1 Ton',
                unitPrice: '$1000',
                totalPrice: '1000000',
                img: prod1
            } ,
            {
                product: 'Steel pipes',
                offeredQuantity: '100 Unit',
                weightUnit: '1 Ton',
                unitPrice: '$1000',
                totalPrice: '1000000',
                img: prod2
            }
        ],
        shopping:{
            shippingTerms: 'FOB',
            leadTime: '4 Week',
            paymentTerms: 'Cash',
        }
    },
    {
        id: "02",
        Img : imgQ1,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        products:  [
            {
                product: 'Steel pipes',
                offeredQuantity: '100 Unit',
                weightUnit: '1 Ton',
                unitPrice: '$1000',
                totalPrice: '1000000',
                img: prod1
            } ,
            {
                product: 'Steel pipes',
                offeredQuantity: '100 Unit',
                weightUnit: '1 Ton',
                unitPrice: '$1000',
                totalPrice: '1000000',
                img: prod2
            }
        ] ,
        shopping:{
            shippingTerms: 'FOB',
            leadTime: '4 Week',
            paymentTerms: 'Cash',
        }
    }
]

export const offers = [
    {
        id: "01",
        Img : imgQ1,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "02",
        Img : imgQ2,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "03",
        Img : imgQ3,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "04",
        Img : imgQ4,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "05",
        Img : imgQ5,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "06",
        Img : imgQ6,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "07",
        Img : imgQ7,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "08",
        Img : imgQ8,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "09",
        Img : imgQ9,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "10",
        Img : imgQ10,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "11",
        Img : imgQ11,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "12",
        Img : imgQ5,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "13",
        Img : imgQ6,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "14",
        Img : imgQ7,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "15",
        Img : imgQ8,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "16",
        Img : imgQ9,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "17",
        Img : imgQ10,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
    {
        id: "18",
        Img : imgQ11,
        name: 'Grey fabrica & materials',
        location: "Lesch Field",
        star: 4.5,
        rating: "347 تقييم",
        isCertified: true,
        product : "Product 1",
        quantity: "1000 Unit",
        paymentMethod : "Cash",
        deliveryDuration : "20/10/2024",
        description : "Offer validity",
        TotalPrice: '2.500 USD'
    },
]

export const contracts = [
    {
        id: "12" ,
        check: true ,
        status: "signed",
        statusText: "Signed",
        title: "Persetujuan pengecoran jalanc...",
        owner: "Me ( junevil )",
        created: "1 Apr 2021",
        chatNum: 10,
        signatory: 2, 
    },
    {
        id: "13" ,
        check: true ,
        status: "pendingLet",
        statusText: "Pending",
        title: "Persetujuan pengecoran jalanc...",
        owner: "Me ( junevil )",
        created: "1 Apr 2021",
        chatNum: 2, 
        signatory: 7,
    },
    {
        id: "14" ,
        check: false ,
        status: "pending",
        statusText: "Pending",
        title: "Persetujuan pengecoran jalanc...",
        owner: "Me ( junevil )",
        created: "1 Apr 2021",
        chatNum: 5, 
        signatory: 5,
    },
    {
        id: "15" ,
        check: false ,
        status: "pendingLet",
        statusText: "Pending",
        title: "Persetujuan pengecoran jalanc...",
        owner: "Me ( junevil )",
        created: "1 Apr 2021",
        chatNum: 1, 
        signatory: 0,
    },
    {
        id: "16" ,
        check: true ,
        status: "pending",
        statusText: "Pending",
        title: "Persetujuan pengecoran jalanc...",
        owner: "Me ( junevil )",
        created: "1 Apr 2021",
        chatNum: 8, 
        signatory: 9,
    },
    {
        id: "17" ,
        check: false ,
        status: "signed",
        statusText: "Signed",
        title: "Persetujuan pengecoran jalanc...",
        owner: "Me ( junevil )",
        created: "1 Apr 2021",
        chatNum: 11,
        signatory: 10, 
    },
    {
        id: "18" ,
        check: false ,
        status: "signed",
        statusText: "Signed",
        title: "Persetujuan pengecoran jalanc...",
        owner: "Me ( junevil )",
        created: "1 Apr 2021",
        chatNum: 0, 
        signatory: 2,
    },
    {
        id: "19" ,
        check: true ,
        status: "pendingLet",
        statusText: "Pending",
        title: "Persetujuan pengecoran jalanc...",
        owner: "Me ( junevil )",
        created: "1 Apr 2021",
        chatNum: 7, 
        signatory: 3,
    },
    {
        id: "20" ,
        check: true ,
        status: "pending",
        statusText: "Pending",
        title: "Persetujuan pengecoran jalanc...",
        owner: "Me ( junevil )",
        created: "1 Apr 2021",
        chatNum: 13,
        signatory: 10, 
    },
]

export const supplier = [
    {
        id: '01',
        name: 'Grey fabrica & materials',
        Img: imgQ7,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '02',
        name: 'Grey fabrica & materials',
        Img: imgQ8,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '03',
        name: 'Grey fabrica & materials',
        Img: imgQ9,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '04',
        name: 'Grey fabrica & materials',
        Img: imgQ10,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '05',
        name: 'Grey fabrica & materials',
        Img: imgQ11,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '06',
        name: 'Grey fabrica & materials',
        Img: imgQ1,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '07',
        name: 'Grey fabrica & materials',
        Img: imgQ2,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '08',
        name: 'Grey fabrica & materials',
        Img: imgQ3,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '09',
        name: 'Grey fabrica & materials',
        Img: imgQ4,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '10',
        name: 'Grey fabrica & materials',
        Img: imgQ5,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '11',
        name: 'Grey fabrica & materials',
        Img: imgQ6,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '12',
        name: 'Grey fabrica & materials',
        Img: imgQ7,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '13',
        name: 'Grey fabrica & materials',
        Img: imgQ8,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '14',
        name: 'Grey fabrica & materials',
        Img: imgQ9,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '15',
        name: 'Grey fabrica & materials',
        Img: imgQ10,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
    {
        id: '16',
        name: 'Grey fabrica & materials',
        Img: imgQ11,
        location: 'Lesch Field',
        rating: '347',
        star: '4.5',
        isCertified: true,
        phoneNumber: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    },
]

export const clients = [
    {   
        id: '010',
        Img: supplierImg ,
        name: 'محمد ثروت' ,
        location: 'Lesch Field' ,
        isActive: true,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
    {   
        id: '020',
        img: supplierImg ,
        name: 'ايهم محمد' ,
        location: 'Lesch Field' ,
        isActive: false,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
    {   
        id: '030',
        img: supplierImg ,
        name: 'علي محمد' ,
        location: 'Lesch Field' ,
        isActive: true,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
    {   
        id: '040',
        img: supplierImg ,
        name: 'حسين علي' ,
        location: 'Lesch Field' ,
        isActive: false,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
    {   
        id: '050',
        img: supplierImg ,
        name: 'محمود حسن' ,
        location: 'Lesch Field' ,
        isActive: true,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
    {   
        id: '060',
        img: supplierImg ,
        name: 'خالد رمضان' ,
        location: 'Lesch Field' ,
        isActive: true,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
]

export const buyers = [
    {   
        id: '010',
        img: supplierImg ,
        name: 'مورد' ,
        location: 'Lesch Field' ,
        rating: 4.5 ,
        isActive: true,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
    {   
        id: '020',
        img: supplierImg ,
        name: 'مورال' ,
        location: 'Lesch Field' ,
        rating: 4.5 ,
        isActive: false,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
    {   
        id: '030',
        img: supplierImg ,
        name: 'النموذجية' ,
        location: 'Lesch Field' ,
        rating: 4.5 ,
        isActive: true,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
    {   
        id: '040',
        img: supplierImg ,
        name: 'مورد' ,
        location: 'Lesch Field' ,
        rating: 4.5 ,
        isActive: false,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
    {   
        id: '050',
        img: supplierImg ,
        name: 'المورد الثقافي' ,
        location: 'Lesch Field' ,
        rating: 4.5 ,
        isActive: true,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
    {   
        id: '060',
        img: supplierImg ,
        name: 'ثقلان' ,
        location: 'Lesch Field' ,
        rating: 4.5 ,
        isActive: true,
        RegistrationDate: '10/12/2024',
        categories: ['الملابس' , 'الأحذية' , 'الأدواة المنزلية' , 'الأدوات الكهربائية واليدوية' , 'المشروبات الغازية'] ,
        notes: 'ملاحظات إضافية أو تعليقات حول المشتري',
        phone: '982-934-4627',
        email: 'Blaise ,Rolfson@hotmail.com'
    } ,
]

export const products = [
    {   
        id: '00',
        img: [
            prod1
        ] ,
        product: 'Steel Pipes',
        category: 'Construction' ,
        minimumOrderQuantity: '20 Tons',
        priceTag: '$150.00 /Ton'
    } ,
    {   
        id: '01',
        img: [
            prod5
        ] ,
        product: 'Steel Pipes',
        category: 'Construction' ,
        minimumOrderQuantity: '20 Tons',
        priceTag: '$150.00 /Ton'
    } ,
    {   
        id: '02',
        img: [
            prod1
        ] ,
        product: 'Steel Pipes',
        category: 'Construction' ,
        minimumOrderQuantity: '20 Tons',
        priceTag: '$150.00 /Ton'
    } ,
    {   
        id: '03',
        img: [
            prod1 , prod2 , prod3 , prod4
        ] ,
        product: 'Steel Pipes',
        category: 'Construction' ,
        minimumOrderQuantity: '20 Tons',
        priceTag: '$150.00 /Ton'
    } ,
    {   
        id: '04',
        img: [
            prod5 , prod6 , prod7 , prod8
        ] ,
        product: 'Steel Pipes',
        category: 'Construction' ,
        minimumOrderQuantity: '20 Tons',
        priceTag: '$150.00 /Ton'
    } ,
    {   
        id: '05',
        img: [
            prod1 , prod2 , prod3 , prod4
        ] ,
        product: 'Steel Pipes',
        category: 'Construction' ,
        minimumOrderQuantity: '20 Tons',
        priceTag: '$150.00 /Ton'
    } ,
]

export const messages = [
    {
        img: supplierImg ,
        name: 'شركة مورد',
        time: '5:19am',
        secondaryText: 'لوريم ايبسوم هو نموذج افتراضي يوضع في التصاميم لتعرض....'
    } ,
    {
        img: supplierImg ,
        name: 'شركة المورد الثقافي' ,
        time: '5:19am',
        secondaryText: 'لوريم ايبسوم هو نموذج افتراضي يوضع في التصاميم لتعرض....'
    } ,
    {
        img: supplierImg ,
        name: 'المورد' ,
        time: '5:19am',
        secondaryText: 'لوريم ايبسوم هو نموذج افتراضي يوضع في التصاميم لتعرض....'
    } ,
    {
        img: supplierImg ,
        name: 'شركة مورد',
        time: '5:19am',
        secondaryText: 'لوريم ايبسوم هو نموذج افتراضي يوضع في التصاميم لتعرض....'
    } 
]

export const notifications = [
    {   
        type: 'accepted',
        text: 'تم الموافقة علي عرض السعر',
        time: '5:19am'
    } ,
    {   
        type: 'rejected',
        text: 'تم رفض علي عرض السعر',
        time: '5:19am'
    } ,
    {   
        type: 'accepted',
        text: 'تم الموافقة علي عرض السعر',
        time: '5:19am'
    } ,
    {   
        type: 'accepted',
        text: 'تم الموافقة علي عرض السعر',
        time: '5:19am'
    } ,
    {   
        type: 'accepted',
        text: 'تم الموافقة علي عرض السعر',
        time: '5:19am'
    } ,
    {   
        type: 'accepted',
        text: 'تم الموافقة علي عرض السعر',
        time: '5:19am'
    } ,
    {   
        type: 'rejected',
        text: 'تم رفض علي عرض السعر',
        time: '5:19am'
    } ,
    {   
        type: 'accepted',
        text: 'تم الموافقة علي عرض السعر',
        time: '5:19am'
    } ,
    {   
        type: 'accepted',
        text: 'تم الموافقة علي عرض السعر',
        time: '5:19am'
    } ,
    {   
        type: 'accepted',
        text: 'تم الموافقة علي عرض السعر',
        time: '5:19am'
    } ,
]